services:
  - type: web
    name: ProyectoAlgoritmosBiblioteca
    env: docker
    region: oregon
    branch: principal
    dockerfilePath: ./Dockerfile
    buildContext: .
    healthCheckPath: /health
    plan: free
