services:
  - type: web
    name: proyecto-algoritmos
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main_fastapi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0